spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:postgres}:5431/render_farm_db
    username: connector
    password: postgres

kafka:
  bootstrap-servers: kafka:29092

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/
