server:
  port: 0

spring:
  application:
    name: task-manager
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: groupId
    listener:
      concurrency: 1
    producer:
      client-id: groupId

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans/
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
